---
abstract: 'Record progress to any output'
author:
  - 'Steven Haryanto <stevenharyanto@gmail.com>'
build_requires:
  Test::Exception: 0
  Test::More: 0.98
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300035, CPAN::Meta::Converter version 2.131560'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Progress-Any
requires:
  Time::Duration: 0
  perl: 5.010001
resources:
  homepage: http://metacpan.org/release/Progress-Any
  repository: http://github.com/sharyanto/perl-Progress-Any
version: 0.12
